const $=s=>document.querySelector(s);
function msg(t){$('#message').textContent=t}
async function j(url,opt){const r=await fetch(url,opt);const d=await r.json().catch(()=>null);return {r,d}}
async function loadWells(){const {r,d}=await j('/api/wells');if(!r.ok){msg('井列表加载失败');return}$('#wells').innerHTML=d.map(w=>`<tr><td>${w.name}</td><td>${w.depth_m} m</td><td>${w.pressure_kpa} kPa</td><td>${w.temperature_c} °C</td><td>${w.status}</td><td><button onclick="setStatus('${w.id}','isolated')">隔离</button><button onclick="setStatus('${w.id}','producing')">恢复</button></td></tr>`).join('')}
async function setStatus(id,status){const {r}=await j('/api/wells/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});msg(r.ok?'井状态已更新':('更新失败 '+status));loadWells()}
async function recent(){const wid=$('#well_id').value||'well-07';const {r,d}=await j('/api/readings/recent?well_id='+encodeURIComponent(wid));if(!r.ok){msg('读数查询失败');return}$('#readings').innerHTML=(d.items||[]).map(x=>`<tr><td>${x.well_id}</td><td>${new Date(x.at).toLocaleString()}</td><td>${x.pressure_kpa}</td><td>${x.temperature_c}</td><td>${x.source}</td></tr>`).join('')||'<tr><td colspan="5">暂无读数</td></tr>'}
async function loadAlerts(){const {r,d}=await j('/api/alerts');if(!r.ok){msg('告警加载失败');return}$('#alerts').innerHTML=(d.items||[]).map(a=>`<tr><td>${a.well_id}</td><td>${a.kind}</td><td>${a.threshold}</td><td>${a.value}</td><td>${new Date(a.at).toLocaleString()}</td><td><button onclick="ack('${a.id}')">确认</button></td></tr>`).join('')||'<tr><td colspan="6">暂无告警</td></tr>'}
async function ack(id){await j('/api/alerts/'+id+'/ack',{method:'POST'});loadAlerts()}
async function loadTasks(){const {r,d}=await j('/api/tasks');if(!r.ok){msg('任务加载失败');return}$('#tasks').innerHTML=(d.items||[]).map(t=>`<tr><td>${t.subject}</td><td>${t.well_id}</td><td>${t.status}</td><td>${t.operator||'-'}</td><td><button onclick="assign('${t.id}')">派单</button><button onclick="complete('${t.id}')">完成</button></td></tr>`).join('')||'<tr><td colspan="5">暂无任务</td></tr>'}
async function createTask(){const well=$('#task_well').value||'well-12';const subject=$('#task_subject').value||'例行巡检';const {r}=await j('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({well_id:well,subject,owner:'web'})});msg(r.ok?'任务已创建':'创建失败');loadTasks()}
async function assign(id){const {r}=await j('/api/tasks/'+id+'/assign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operator:'liang'})});msg(r.ok?'已派单':'派单失败');loadTasks()}
async function complete(id){const {r}=await j('/api/tasks/'+id+'/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operator:'liang'})});msg(r.ok?'已完成':'完成失败');loadTasks()}
loadWells();recent();loadAlerts();loadTasks();
